import React, { useState } from 'react';
import Sidebar from './components/Sidebar';
import ChatWindow from './components/ChatWindow';
import { INITIAL_CONVERSATIONS, CURRENT_USER } from './constants';
import { Conversation, Message } from './types';
import { Instagram, Search, Home, Compass, Heart, PlusSquare, Menu, MessageCircle } from 'lucide-react';

const App: React.FC = () => {
  const [conversations, setConversations] = useState<Conversation[]>(INITIAL_CONVERSATIONS);
  const [activeId, setActiveId] = useState<string>(INITIAL_CONVERSATIONS[0].id);

  const activeConversation = conversations.find(c => c.id === activeId) || conversations[0];

  const handleSendMessage = (text: string) => {
    const newMessage: Message = {
      id: `new-${Date.now()}`,
      senderId: CURRENT_USER.id,
      text: text,
      timestamp: Date.now(),
      isOwn: true
    };

    setConversations(prev => prev.map(conv => {
      if (conv.id === activeId) {
        return {
          ...conv,
          messages: [...conv.messages, newMessage],
          lastMessagePreview: text,
          lastMessageTime: Date.now(),
        };
      }
      return conv;
    }));
  };

  return (
    <div className="flex h-screen w-full bg-white md:bg-gray-50">
      
      {/* Main Navigation Rail (Leftmost on desktop) */}
      <div className="hidden md:flex flex-col w-[72px] xl:w-[244px] border-r border-gray-200 bg-white h-full pt-8 pb-5 px-3">
        {/* Logo */}
        <div className="mb-8 pl-2 xl:pl-2">
            <Instagram className="block xl:hidden w-6 h-6" />
             {/* Instagram Text Logo Mock for wider screens */}
             <div className="hidden xl:block font-['Inter'] italic font-bold text-2xl">Instagram</div>
        </div>
        
        <div className="flex-1 space-y-2">
           <NavItem icon={<Home size={24} />} label="Home" />
           <NavItem icon={<Search size={24} />} label="Search" />
           <NavItem icon={<Compass size={24} />} label="Explore" />
           <NavItem icon={<MessageCircle size={24} />} label="Messages" active />
           <NavItem icon={<Heart size={24} />} label="Notifications" />
           <NavItem icon={<PlusSquare size={24} />} label="Create" />
           <div className="mt-auto pt-10">
              <div className="flex items-center p-3 rounded-lg hover:bg-gray-100 cursor-pointer transition-colors">
                <img src={CURRENT_USER.avatar} className="w-6 h-6 rounded-full" alt="Profile" />
                <span className="hidden xl:block ml-4 font-medium text-base">Profile</span>
              </div>
           </div>
        </div>

        <div className="mt-auto">
           <NavItem icon={<Menu size={24} />} label="More" />
        </div>
      </div>

      {/* Direct Messages Container */}
      <div className="flex flex-1 h-full overflow-hidden md:my-0">
         {/* Sidebar: Conversation List */}
         <div className={`h-full w-full md:w-auto ${activeId ? 'hidden md:block' : 'block'}`}>
            <Sidebar 
              conversations={conversations} 
              activeId={activeId} 
              onSelect={setActiveId} 
            />
         </div>

         {/* Chat Window */}
         <div className={`flex-1 h-full flex flex-col ${!activeId ? 'hidden md:flex' : 'block'}`}>
            {activeConversation ? (
               <ChatWindow 
                 conversation={activeConversation} 
                 currentUser={CURRENT_USER}
                 onSendMessage={handleSendMessage}
               />
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center bg-white">
                 <div className="w-24 h-24 rounded-full border-2 border-black flex items-center justify-center mb-4">
                    <MessageCircle size={48} />
                 </div>
                 <h2 className="text-xl font-medium mb-2">Your Messages</h2>
                 <p className="text-gray-500 text-sm mb-4">Send private photos and messages to a friend or group.</p>
                 <button className="bg-[#0095f6] text-white px-4 py-1.5 rounded text-sm font-semibold">
                   Send Message
                 </button>
              </div>
            )}
         </div>
      </div>

      {/* Mobile Disclaimer (Overlay or Toast) */}
      <div className="fixed bottom-4 right-4 max-w-xs bg-gray-900 text-white text-xs p-3 rounded opacity-70 pointer-events-none z-50 hidden md:block">
        <p><strong>Simulation Mode:</strong> This interface uses Mock Data. AI replies are generated by Gemini.</p>
      </div>

    </div>
  );
};

// Helper for Nav Items
const NavItem = ({ icon, label, active = false }: { icon: React.ReactNode, label: string, active?: boolean }) => (
  <div className={`flex items-center p-3 rounded-lg cursor-pointer transition-all duration-200 group ${active ? 'font-bold' : 'font-normal hover:bg-gray-100'}`}>
    <div className={`group-hover:scale-105 transition-transform ${active ? 'scale-105' : ''}`}>
      {icon}
    </div>
    <span className={`hidden xl:block ml-4 text-base ${active ? 'font-bold' : ''}`}>{label}</span>
  </div>
);

export default App;